import type { MermaidConfig } from 'mermaid'

export const lightConfig: MermaidConfig = {
  startOnLoad: false,
  theme: 'default',
  themeVariables: {
    fontFamily: '"Inter", "SF Pro Display", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    fontSize: '13px',
    // 甘特图专用变量
    cScale0: '#4F8CF7',
    cScale1: '#7C5CFC',
    cScale2: '#F7704F',
    cScale3: '#2ECDA7',
    cScale4: '#F5A623',
    cScale5: '#E84393',
    cScale6: '#00B894',
    cScale7: '#6C5CE7',
    cScaleLabel0: '#ffffff',
    cScaleLabel1: '#ffffff',
    cScaleLabel2: '#ffffff',
    cScaleLabel3: '#ffffff',
    cScaleLabel4: '#ffffff',
    cScaleLabel5: '#ffffff',
    cScaleLabel6: '#ffffff',
    cScaleLabel7: '#ffffff',
    ganttTaskColor: '#4F8CF7',
    ganttTaskTextOutsideColor: '#555',
    ganttActiveTaskColor: '#7C5CFC',
    ganttDoneTaskColor: '#2ECDA7',
    ganttCritTaskColor: '#F7704F',
    ganttTodayLineColor: '#E84393',
    ganttSectionBkg: '#f8f9fc',
    ganttSectionBkg0: '#f0f4ff',
    ganttSectionBkg1: '#f5f0ff',
    ganttSectionBkg2: '#fff5f2',
    ganttSectionBkg3: '#f0fdf8',
    ganttActiveTaskBkg: '#7C5CFC',
    ganttActiveTaskBorderColor: '#6344E0',
    ganttDoneTaskBkg: '#2ECDA7',
    ganttDoneTaskBorderColor: '#25B592',
    ganttCritTaskBkg: '#F7704F',
    ganttCritBorderColor: '#E05A3A',
    ganttTaskBkg: '#4F8CF7',
    ganttTaskBorderColor: '#3A75E0',
    ganttGridColor: '#e8ecf2',
    ganttTitleColor: '#1a202c',
    ganttTitleFontSize: '18px',
    ganttSectionColor: '#4a5568',
    ganttLineColor: '#cbd5e0',
  },
  gantt: {
    titleTopMargin: 30,
    barHeight: 24,
    barGap: 6,
    topPadding: 60,
    leftPadding: 100,
    gridLineStartPadding: 40,
    fontSize: 13,
    sectionFontSize: 13,
    numberSectionStyles: 4,
    axisFormat: '%Y-%m-%d',
    useWidth: 1200,
  },
  securityLevel: 'loose',
}

export const darkConfig: MermaidConfig = {
  ...lightConfig,
  theme: 'dark',
  themeVariables: {
    ...(lightConfig.themeVariables as Record<string, string>),
    ganttSectionBkg: '#1e2538',
    ganttSectionBkg0: '#1a2340',
    ganttSectionBkg1: '#251a40',
    ganttSectionBkg2: '#401a1a',
    ganttSectionBkg3: '#1a4030',
    ganttActiveTaskBkg: '#7C5CFC',
    ganttActiveTaskBorderColor: '#9B7FFF',
    ganttDoneTaskBkg: '#2ECDA7',
    ganttDoneTaskBorderColor: '#4FE0BC',
    ganttCritTaskBkg: '#F7704F',
    ganttCritBorderColor: '#FF9580',
    ganttTaskBkg: '#4F8CF7',
    ganttTaskBorderColor: '#6FA3FF',
    ganttGridColor: '#2d3748',
    ganttTitleColor: '#e2e8f0',
    ganttSectionColor: '#a0aec0',
    ganttLineColor: '#4a5568',
    ganttTaskTextOutsideColor: '#a0aec0',
  },
}

export const getMermaidConfig = (theme: 'light' | 'dark'): MermaidConfig => {
  return theme === 'dark' ? darkConfig : lightConfig
}
